<html>
<body>
<h1> WEB DESIGN TUTORIAL</h1>
<p> to design a website, 
How to Make a Website 
1. Sign up for a website builder 
2. Select a template 
3. Pick a domain name 
4. Upload content 
5. Design your site 
6. Consider Ecommerce options 
7. Set up marketing and analytics 
8. Share it with the world </p>
<P><br /> <b>WEB DESIGN</b> <p>
<hr />
<p>This week being the 4<sup>the</sup> of August<sub>,</sub> we’re looking at work proposals, what to consider, what to include in your price quote, and a pricing system for your services, especially if you’re building websites with Elementor.
</body>
</html>
