<html>
<body>
<h1> WEB DESIGN TUTORIAL</h1>
<p> to design a website, How to Make a Website 1. Sign up for a website builder 2. Select a template 3. Pick a domain name 4. Upload content 5. Design your site 6. Consider Ecommerce options 7. Set up marketing and analytics 8. Share it with the world </p>
</body>
</html>
